[package]
name = "ffi-string"
version = "1.0.1"
edition = "2021"
license = "MIT"
description = "A small crate for moving strings across `extern \"C\"`"
repository = "https://github.com/What42Pizza/ffi-string"
readme = "readme.md"
keywords = ["ffi"]
